### ISSUE TITLE
windows上无法安装

### ISSUE THREAD

**Issue by shithead548** [hetong007/pullword#1]
错误如下：

> Downloading github repo hetong007/pullword@master
> Installing pullword
> "C:/PROGRA~1/R/R-31~1.2/bin/x64/R" --vanilla CMD INSTALL  \
>   "C:/Users/Administrator/AppData/Local/Temp/RtmpqOiq5m/devtools1e7064be23ab/hetong007-pullword-ad21875"  \
>   --library="C:/Users/Administrator/Documents/R/win-library/3.1" --install-tests 
> - installing _source_ package 'pullword' ...
>   *\* libs
>   **\* arch - i386
>   警告: 运行命令'make -f "C:/PROGRA~1/R/R-31~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-31~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="pullword.dll" OBJECTS="tmcn_encoding_isbig5.o tmcn_encoding_isgb18030.o tmcn_encoding_isgb2312.o tmcn_encoding_isgbk.o tmcn_encoding_isutf8.o"'的状态是127
>   ERROR: compilation failed for package 'pullword'
> - removing 'C:/Users/Administrator/Documents/R/win-library/3.1/pullword'
>   Error: Command failed (1)

**Comment by hetong007** [comment]
你好，内含需要编译的代码，请安装[Rtools](http://cran.r-project.org/bin/windows/Rtools/).
